Introdotto meccanismo gestione ed invio metriche Prometheus.
Aggiunto file VERSION e file CHANGELOG.md.

diff --git a/docker_conf/init b/docker_conf/init
--- a/docker_conf/init
+++ b/docker_conf/init
@@ -41,6 +41,11 @@ if [ -z "${SERVER_HOST}" ] || [ -z "${EPAS_CLIENT_USER}" ] || [ -z "${EPAS_CLIEN
     exit 1
 fi
 
+if [ "${METRICS_ENABLED}" == "True"] && [ -z "${METRICS_PUSHGATEWAY_URL}" ]; then
+    echo "ERROR: "
+    echo "Per favore specifica l'url del pushgateway a cui inviare le metriche tramite il parametro METRCS_PUSHGATEWAY_URL"
+    exit 1
+
 STAMPINGS_SERVER_PROTOCOL=${STAMPINGS_SERVER_PROTOCOL:-smartclock}
 STAMPINGS_ON_LOCAL_FOLDER=${STAMPINGS_ON_LOCAL_FOLDER:-False}
 
@@ -83,6 +88,11 @@ MAX_THREADS=${MAX_THREADS:-1}
 DAYS_TO_DOWNLOAD=${DAYS_TO_DOWNLOAD:-10}
 MAX_BAD_STAMPING_DAYS=${MAX_BAD_STAMPING_DAYS:-10}
 SERVER_ERROR_CODES=${SERVER_ERROR_CODES:-401, 404, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509}
+
+METRICS_ENABLED=${METRICS_ENABLED:-False}
+METRICS_PUSHGATEWAY_URL=${METRICS_PUSHGATEWAY_URL}
+METRICS_PUSHGATEWAY_USER=${METRICS_PUSHGATEWAY_USER}
+METRICS_PUSHGATEWAY_PASSWORD=${METRICS_PUSHGATEWAY_PASSWORD}
 
 cp /client/docker_conf/config.py /client/epas_client/
 
